create table twf.stdexp_ot(
	ID INT NOT NULL AUTO_INCREMENT,
	Record_Type VARCHAR(45) NOT NULL,
	StoreID VARCHAR(45) NOT NULL,
	Date Date NOT NULL,
    RVC_num INT,
    OT_Number INT,
    OT_Name VARCHAR(45),
    OT_Count INT,
    OT_TotalDayNetSales DECIMAL(15,6),
    OT_TotalGuests INT,
    OT_TablesTurned INT,
    OT_MasterName VARCHAR(45),
    OT_MasterNum INT,
    OT_TotalByPeriod INT,
    RVC_name VARCHAR(45),
    RVC_MasterName VARCHAR(45),
    RVC_MasterNum INT,
    OT_TotalDayTables INT,
    OT_ServiceCharge DECIMAL(15,6),
    OT_TableTime INT,
    OT_TotalPrepCost DECIMAL(15,6),
    OT_TotalDayReturns DECIMAL(15,6),
    OT_CountDayReturns INT,
    OT_TotalDayVoid DECIMAL(15,6),
    OT_TotalDayVoidCount INT,
    OT_ManagerVoidTotal DECIMAL(15,6),
    OT_ManagerVoidCount INT,
    OT_CancelAmount DECIMAL(15,6),
    OT_CancelCount INT,
    OT_ErrorCorrectTotal DECIMAL(15,6),
    OT_ErrorCorrectCount INT,
    OT_CheckOpenCount INT,
    OT_CHeckClosedCount INT,
    OT_Checks_inProgress INT,
    OT_GrossS_beforediscount DECIMAL(15,6),
    OT_TotalDscnt DECIMAL(15,6),
	PRIMARY KEY(ID)
);