create table twf.stdexp_sum(
	ID INT NOT NULL AUTO_INCREMENT,
	Record_Type VARCHAR(45) NOT NULL,
	StoreID VARCHAR(45) NOT NULL,
	Date Date NOT NULL,
    RVC_num INT,
	RVC_name VARCHAR(45),
    SUM_TotalDayNetSales DECIMAL(15,6),
    SUM_TotalDiscount DECIMAL(15,6),
    SUM_TotalDaySrvcChrg DECIMAL(15,6),
    SUM_TotalDayVoid DECIMAL(15,6),
    SUM_TotalDayVoidCount INT,
    SUM_TotalDayReturns DECIMAL(15,6),
    SUM_TotalDayReturnCount INT,
    SUM_TotalDayTax DECIMAL(15,6),
    SUM_NonTaxableSls DECIMAL(15,6),
    SUM_TotalExemptTax DECIMAL(15,6),
    SUM_TotalDayTransactions INT,
    SUM_TotalDayGuests INT,
    SUM_TablesTurned INT,
    SUM_TotalOrderTime INT,
    SUM_Total_OverShort DECIMAL(15,6),
    SUM_ForecastedSls DECIMAL(15,6),
    RVC_MasterName VARCHAR(45),
    RVC_MasterNum INT,
    SUM_Weather VARCHAR(45),
    SUM_HighTemperature INT,
    SUM_LowTemperature INT,
    SUM_GrossS_beforediscount DECIMAL(15,6),
    SUM_GrossVatDiscount DECIMAL(15,6),
    SUM_TotalVat DECIMAL(15,6),
    SUM_NetSlsVat DECIMAL(15,6),
    SUM_TotalCredit DECIMAL(15,6),
    SUM_TotalCostSls DECIMAL(15,6),
    SUM_PrepCost DECIMAL(15,6),
    SUM_TotalDayTables INT,
    SUM_LastYearSls DECIMAL(15,6),
    SUM_LastYearGuests INT,
    SUM_LastYearChecks INT,
    SUM_ForecastedGrossSls DECIMAL(15,6),
    SUM_ForecastedNetSls DECIMAL(15,6),
    SUM_ForecastedTotalDscnt DECIMAL(15,6),
    SUM_ForecastedTotalChecks DECIMAL(15,6),
    SUM_ForecastedTotalTables DECIMAL(15,6),
    SUM_ForecastedAvgGuests DECIMAL(15,6),
    SUM_ForecastedSlsNetVatBeforeDscnt DECIMAL(15,6),
    SUM_ForecastedSlsNetVatAfterDscnt DECIMAL(15,6),
    SUM_TableTime INT,
    SUM_ErrorCorrectTotal DECIMAL(15,6),
    SUM_ErrorCorrectCount INT,
    SUM_MngrVoidAmount DECIMAL(15,6),
    SUM_MngrVoidCount INT,
    SUM_CancelAmount DECIMAL(15,6),
    SUM_CancelCount INT,
    SUM_ChecksOpenAmount DECIMAL(15,6),
    SUM_ChecksOpenCount INT,
    SUM_ChecksClosedAmount DECIMAL(15,6),
    SUM_ChecksClosedCount INT,
    SUM_ChecksTransferInAmount DECIMAL(15,6),
    SUM_ChecksTransferInCount INT,
    SUM_ChecksTransferOutAmount DECIMAL(15,6),
    SUM_ChecksTransferOutCount INT,
    SUM_NonRevenueSrvcChrg DECIMAL(15,6),
	PRIMARY KEY(ID)
);