create table twf.stdexp_emp(
	ID INT NOT NULL AUTO_INCREMENT,
	Record_Type VARCHAR(45) NOT NULL,
	StoreID VARCHAR(45) NOT NULL,
	Date Date NOT NULL,
	RVC_name VARCHAR(45),
	RVC_num int,
	RVC_MasterName VARCHAR(45),
	RVC_MasterNum int,
	EMP_name VARCHAR(45),
	EMP_Surname VARCHAR(45),
	EMP_number int,
	EMP_TotalDayTransactions int,
	EMP_TotalDayGuests int,
	EMP_TablesTurned int,
	EMP_TableTime int,
	EMP_TotalDayNetSales decimal(15,6),
	EMP_TotalDaySrvcChrg decimal(15,6),
	EMP_TotalDayVoid decimal(15,6),
	EMP_TotalDayVoidCount int,
	EMP_TotalDayReturns decimal(15,6),
	EMP_TotalDayReturnCount int,
	EMP_Credit decimal(15,6),
	EMP_Round decimal(15,6),
	EMP_ErrorCorrectAmount decimal(15,6),
	EMP_ErrorCorrectCount int,
	EMP_MngrVoidAmount decimal(15,6),
	EMP_MngrVoidCount int,
	EMP_CancelAmount decimal(15,6),
	EMP_CancelCount int,
	EMP_ChecksOpenAmount decimal(15,6),
	EMP_ChecksOpenCount int,
	EMP_ChecksClosedAmount decimal(15,6),
	EMP_ChecksClosedCount int,
	EMP_ChecksTransferInAmount decimal(15,6),
	EMP_ChecksTransferInCount int,
	EMP_ChecksTransferOutAmount decimal(15,6),
	EMP_ChecksTransferOutCount int,
	EMP_NonRevenueSrvcChrg decimal(15,6),
	EMP_TipTotal decimal(15,6),
	EMP_Cary_Over_Total decimal(15,6),
	EMP_Cary_Over_Count int,
	EMP_GrossS_beforediscount decimal(15,6),
	EMP_DSC_total decimal(15,6),
	EMP_DSC_GrossVat decimal(15,6),
	EMP_GrossS decimal(15,6),
	PRIMARY KEY(ID)
);