create table twf.stdexp_mnpr(
	ID INT NOT NULL AUTO_INCREMENT,
	Record_Type VARCHAR(45) NOT NULL,
	StoreID VARCHAR(45) NOT NULL,
	Date Date NOT NULL,
    RVC_num INT,
    MI_number INT,
    MNPR_LvlPrice INT,
    MNPR_LvlName VARCHAR(45),
    MNPR_Price DECIMAL(15,6),
    MNPR_Cost DECIMAL(15,6),
    MNPR_Efectivity Date,
    MNPR_TaxClassNumber INT,
    MNPR_MenuLvl INT,
    RVC_name VARCHAR(45),
    RVC_MasterName VARCHAR(45),
    RVC_MasterNum INT,
    MI_name VARCHAR(45),
    MI_MasterName VARCHAR(45),
    MI_MasterNum INT,
    MNPR_majorgroup_name VARCHAR(45),
    MNPR_majorgroup_number INT,
    MNPR_MasterMajorgroup_name VARCHAR(45),
    MI_Master_majorgroup_number INT,
    MNPR_familygroup_name VARCHAR(45),
    MNPR_familygroup_num INT,
    MNPR_Master_familygroup_name VARCHAR(45),
    MNPR_Master_familygroup_num INT,
	PRIMARY KEY(ID)
);