create table twf.stdexp_mid(
	ID INT NOT NULL AUTO_INCREMENT,
	Record_Type VARCHAR(45) NOT NULL,
	StoreID VARCHAR(45) NOT NULL,
	Date Date NOT NULL,
    RVC_num INT,
    OT_number DECIMAL(15,6),
    MI_number INT,
    MI_Name VARCHAR(45),
    MI_pricelevel INT,
    MI_SlsCount INT,
    MI_SlsTotal DECIMAL(15,6),
    MI_TotalDscnt DECIMAL(15,6),
    MI_ReturnCount DECIMAL(15,6),
    MI_volume DECIMAL(15,6),
    MI_PrepCost DECIMAL(15,6),
    MI_MasterName VARCHAR(45),
    MI_MasterNumber INT,
    RVC_name VARCHAR(45),
    RVC_MasterName VARCHAR(45),
    RVC_MasterNum INT,
    MI_name2 VARCHAR(45),
    MI_MasterName2 VARCHAR(45),
    MI_majorgroup_name VARCHAR(45),
    MI_majorgroup_number INT,
    MI_MasterMajorgroup_name VARCHAR(45),
    MI_Master_majorgroup_number INT,
    MI_familygroup_name VARCHAR(45),
    MI_familygroup_num INT,
    MI_Master_familygroup_name VARCHAR(45),
    MI_Master_familygroup_num INT,
    OT_name VARCHAR(45),
    OT_MasterName VARCHAR(45),
    OT_MasterNum INT,
    MI_GrossS_beforediscount DECIMAL(15,6),
    DSC_GrossVat DECIMAL(15,6),
    MI_GrossS_afterdiscount DECIMAL(15,6),
    MI_VAT_beforediscount DECIMAL(15,6),
    MI_DscntVat DECIMAL(15,6),
    MI_VatAfterDscnt DECIMAL(15,6),
    MI_TotalVat DECIMAL(15,6),
    MI_NetSales_beforediscount DECIMAL(15,6),
    MI_DscntNetVat DECIMAL(15,6),
    MI_SlsNetVat DECIMAL(15,6),
	PRIMARY KEY(ID)
);