create table twf.stdexp_pay(
	ID INT NOT NULL AUTO_INCREMENT,
	Record_Type VARCHAR(45) NOT NULL,
	StoreID VARCHAR(45) NOT NULL,
	Date Date NOT NULL,
	PAY_ID VARCHAR(45),
	PAY_BusinessDate DATE,
	PAY_JobCodeNumber INT,
	PAY_JobCodeName VARCHAR(45),
	PAY_RegularHour DECIMAL(15,6),
	PAY_RegularPay DECIMAL(15,6),
	PAY_OvertimeHour1 DECIMAL(15,6),
	PAY_OvertimePay1 DECIMAL(15,6),
	PAY_OvertimeHourOther DECIMAL(15,6),
	PAY_OvertimePayOther DECIMAL(15,6),
	PAY_OtherType VARCHAR(45),
	PAY_OtherHour DECIMAL(15,6),
	PAY_OtherPay DECIMAL(15,6),
	PAY_OtherPayRate DECIMAL(15,6),
	PAY_F_BGrossReceipts DECIMAL(15,6),
	PAY_TotalTipsPaid DECIMAL(15,6),
	PAY_TotalChargedReceipts DECIMAL(15,6),
	PAY_TotalChargedTips DECIMAL(15,6),
	PAY_Total_IndirectTips DECIMAL(15,6),
	PAY_TotalDeclareTips DECIMAL(15,6),
	PAY_HomeStore VARCHAR(45),
	PAY_NonRVC_RegularHour DECIMAL(15,6),
	PAY_NonRVC_RegularPay DECIMAL(15,6),
	PAY_NonRVC_OvertimeHour DECIMAL(15,6),
	PAY_NonRVC_OvertimePay DECIMAL(15,6),
	PAY_OtherPayDescription VARCHAR(45),
	RVC_name VARCHAR(45),
	RVC_num INT,
	RVC_MasterName VARCHAR(45),
	RVC_MasterNum INT,
	EMP_name VARCHAR(45),
	EMP_Surname VARCHAR(45),
	EMP_number INT,
	PAY_JobCodeMasterName VARCHAR(45),
	PAY_JobCodeMasterNum INT,
	PAY_ServiceTips DECIMAL(15,6),
	PAY_CashTups DECIMAL(15,6),
	PAY_TotalTips DECIMAL(15,6),
	PAY_TotalDaySrvcChrg DECIMAL(15,6),
	PAY_OvertimeHour2 DECIMAL(15,6),
	PAY_OvertimePay2 DECIMAL(15,6),
	PAY_OvertimeHour3 DECIMAL(15,6),
	PAY_OvertimePay3 DECIMAL(15,6),
	PAY_OvertimeHour4 DECIMAL(15,6),
	PAY_OvertimePay4 DECIMAL(15,6),
	PAY_GrossS_beforediscount DECIMAL(15,6),
	PAY_GrossVatDiscount DECIMAL(15,6),
	PAY_GrossSlsAfterDscnt DECIMAL(15,6),
	PAY_ExternalPayroll_ID VARCHAR(45),
	PRIMARY KEY(ID)
);