create table twf.stdexp_rcpt(
	ID INT NOT NULL AUTO_INCREMENT,
	Record_Type VARCHAR(45) NOT NULL,
	StoreID VARCHAR(45) NOT NULL,
	Date Date NOT NULL,
    RCPT_ReceiptNumber INT,
    RCPT_VendorName VARCHAR(45),
    RCPT_VendorNumber INT,
    RCPT_VendorMasterName VARCHAR(45),
    RCPT_VendorMasterNumber INT,
    RCPT_VendorAddress1 VARCHAR(45),
    RCPT_VendorAddress2 VARCHAR(45),
    RCPT_VendorCity VARCHAR(45),
    RCPT_ReceiptReceivedBy VARCHAR(45),
    RCPT_ReceiptStatus INT,
    RCPT_InvoiceDoc VARCHAR(45),
    RCPT_PackingDoc VARCHAR(45),
    RCPT_PackingDate DATE,
    RCPT_TotalAdjusted DECIMAL(15,6),
    RCPT_InvoiceDate DATE,
    RCPT_InvoiceTotal DECIMAL(15,6),
    RCPT_PurchaseOrderCreatedBy VARCHAR(45),
    RCPT_PurchaseOrderNum INT,
    RCPT_PurchaseOrderStatus INT,
    RCPT_PurchaseOrderDate DATE,
	PRIMARY KEY(ID)
);