create table twf.stdexp_fpsum(
	ID INT NOT NULL AUTO_INCREMENT,
	Record_Type VARCHAR(45) NOT NULL,
	StoreID VARCHAR(45) NOT NULL,
	Date Date NOT NULL,
    RVC_name VARCHAR(45),
    RVC_num INT,
    RVC_MasterName VARCHAR(45),
    RVC_MasterNum INT,
    SUM_TotalDayNetSales DECIMAL(15,6),
    SUM_TotalDaySrvcChrg DECIMAL(15,6),
    SUM_TotalDayVoid DECIMAL(15,6),
    SUM_TotalDayVoidCount INT,
    SUM_TotalDayReturns DECIMAL(15,6),
    SUM_CountDayReturns INT,
    SUM_TotalDayTax DECIMAL(15,6),
    SUM_TotalDayTransactions INT,
    SUM_TotalDayGuests INT,
    SUM_TablesTurned INT,
    SUM_TotalDayTables INT,
    SUM_TotalOrderTime INT,
    SUM_ForecastedSls DECIMAL(15,6),
    SUM_PrepCost DECIMAL(15,6),
    SUM_LastYearSls DECIMAL(15,6),
    SUM_LastYearGuests INT,
    SUM_LastYearChecks INT,
    SUM_TableTime INT,
    SUM_ErrorCorrectTotal DECIMAL(15,6),
    SUM_ErrorCorrectCount INT,
    SUM_MngrVoidAmount DECIMAL(15,6),
    SUM_MngrVoidCount INT,
    SUM_CancelAmount DECIMAL(15,6),
    SUM_CancelCount INT,
    SUM_ChecksOpenAmount DECIMAL(15,6),
    SUM_ChecksOpenCount INT,
    SUM_ChecksClosedAmount DECIMAL(15,6),
    SUM_ChecksClosedCount INT,
    SUM_ChecksTransferInAmount DECIMAL(15,6),
    SUM_ChecksTransferInCount INT,
    SUM_ChecksTransferOutAmount DECIMAL(15,6),
    SUM_ChecksTransferOutCount INT,
    SUM_NonRevenueSrvcChrg DECIMAL(15,6),
    SUM_Credit DECIMAL(15,6),
    SUM_Hour INT,
    SUM_FixedPeriod INT,
    SUM_GrossS_beforediscount DECIMAL(15,6),
    SUM_TotalDscnt DECIMAL(15,6),
    SUM_DscntGrossVat DECIMAL(15,6),
    SUM_VAT_total DECIMAL(15,6),
    SUM_NetSales DECIMAL(15,6),
    SUM_ForecastedGrossSls DECIMAL(15,6),
    SUM_ForecastedNetSls DECIMAL(15,6),
    SUM_ForecastedTotalDscnt DECIMAL(15,6),
    SUM_ForecastedTotalChecks DECIMAL(15,6),
    SUM_ForecastedTableTurns DECIMAL(15,6),
    SUM_ForecastedAvgTotalChecks DECIMAL(15,6),
    SUM_ForecastedSlsNetVatBeforeDscnt DECIMAL(15,6),
    SUM_ForecastedSlsNetVatAfterDscnt DECIMAL(15,6),
	PRIMARY KEY(ID)
);