create table twf.stdexp_inv(
	ID INT NOT NULL AUTO_INCREMENT,
	Record_Type VARCHAR(45) NOT NULL,
	StoreID VARCHAR(45) NOT NULL,
	Date Date NOT NULL,
    INV_ItemName1 VARCHAR(45),
    INV_ItemName2 VARCHAR(45),
    INV_ItemNameNum INT,
    INV_ItemMasterName1 VARCHAR(45),
    INV_ItemMasterName2 VARCHAR(45),
    INV_ItemMasterNum INT,
    INV_Type INT,
    INV_CostCenterName VARCHAR(45),
    INV_CostCenterNum INT,
    INV_CostCenterMasterName VARCHAR(45),
    INV_CostCenterMasterNum INT,
    INV_CostGroupName VARCHAR(45),
    INV_CostGroupNumber INT,
    INV_CostGroupMasterName VARCHAR(45),
    INV_CostGroupMasterNum INT,
    INV_StandardUnitMeasureName VARCHAR(45),
    INV_StandardUnitMeasureNum INT,
    INV_StandardUnitMeasureMasterName VARCHAR(45),
    INV_StandardUnitMeasureMasterNum INT,
    INV_BaseUnitMeasureName VARCHAR(45),
    INV_BaseUnitMeasureNum INT,
    INV_BaseUnitMeasureMasterName VARCHAR(45),
    INV_BaseUnitMeasureMasterNum INT,
    INV_OnHandQuantity DECIMAL(15,6),
    INV_OnHandValue DECIMAL(15,6),
    INV_ReceiptQuantity DECIMAL(15,6),
    INV_ReceiptValue DECIMAL(15,6),
    INV_UsageQuantity DECIMAL(15,6),
    INV_ProductionUsageQuantity DECIMAL(15,6),
    INV_ProductionReceiptQuantity DECIMAL(15,6),
    INV_ProductionReceiptValue DECIMAL(15,6),
    INV_TransferInQuantity DECIMAL(15,6),
    INV_TransferInValue DECIMAL(15,6),
    INV_TransferOutQuantity DECIMAL(15,6),
    INV_VarianceQuantity DECIMAL(15,6),
    INV_CountedQuantity DECIMAL(15,6),
    INV_CountedTime Date,
	PRIMARY KEY(ID)
);