create table twf.stdexp_nonsls(
	ID INT NOT NULL AUTO_INCREMENT,
	Record_Type VARCHAR(45) NOT NULL,
	StoreID VARCHAR(45) NOT NULL,
	Date Date NOT NULL,
    RVC_name VARCHAR(45),
    RVC_num INT,
    RVC_MasterName VARCHAR(45),
    RVC_MasterNum INT,
    EMP_name VARCHAR(45),
    EMP_Surname VARCHAR(45),
    EMP_number INT,
    EMP_ShiftNumber INT,
    NON_WorkstationName VARCHAR(45),
    NON_WorkstationNum INT,
    NON_ReasonCodeName VARCHAR(45),
    NON_ReasonCodeNum INT,
    NON_ReasonCodeMasterName VARCHAR(45),
    NON_ReasonCodeMasterNum INT,
    NON_CashierName VARCHAR(45),
    NON_CashierNum INT,
    NON_CashierMasterName VARCHAR(45),
    NON_CashierMasterNum INT,
    NON_CashierShiftNum INT,
    NON_CashierDrawerNum INT,
    NON_TransactionDate DECIMAL(15,6),
    NON_FixedPeriod INT,
    NON_SlsType VARCHAR(45),
    NON_Reference VARCHAR(45),
    NON_TotalAmount DECIMAL(15,6),
    NON_TotalCount INT,
    NON_TotalCancelCount INT,
    NON_TotalCancel DECIMAL(15,6),
	PRIMARY KEY(ID)
);

